# https://taskfile.dev

version: '3'

vars:
  VERSION_FILE: VERSION
  CHART_PATH: deploy/charts/release-flow-test

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  release:
    desc: Create a new release PR
    aliases: [rc]
    interactive: true
    silent: true
    env:
      VERSION_FILE: "{{.VERSION_FILE}}"
      CHART_PATH: "{{.CHART_PATH}}"
    cmds:
      - ./scripts/release.sh

  release-status:
    desc: Show the status of the current release
    silent: true
    cmds:
      - |
        #!/bin/bash
        set -e

        BLUE='\033[0;34m'
        GREEN='\033[0;32m'
        YELLOW='\033[1;33m'
        NC='\033[0m'

        echo -e "${BLUE}=== Release Status ===${NC}"
        echo ""

        # Current VERSION
        if [ -f "{{.VERSION_FILE}}" ]; then
          VERSION=$(cat {{.VERSION_FILE}} | tr -d '[:space:]')
          echo -e "VERSION file: ${GREEN}${VERSION}${NC}"
        else
          echo -e "VERSION file: ${YELLOW}not found${NC}"
        fi

        # Latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
        echo -e "Latest tag: ${GREEN}${LATEST_TAG}${NC}"

        # Open release PRs
        echo ""
        echo "Open release PRs:"
        gh pr list --label release --json number,title,url --template '{{range .}}  #{{.number}} {{.title}}{{"\n"}}    {{.url}}{{"\n"}}{{end}}' 2>/dev/null || echo "  None"

        # Recent releases
        echo ""
        echo "Recent releases:"
        gh release list --limit 5 2>/dev/null || echo "  None"

  version:
    desc: Show the current version
    silent: true
    cmds:
      - cat {{.VERSION_FILE}}
