# https://taskfile.dev

version: '3'

vars:
  VERSION_FILE: VERSION

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  release-candidate:
    desc: Create a new release candidate tag
    aliases: [rc]
    interactive: true
    silent: true
    cmds:
      - |
        #!/bin/bash
        set -e

        # Colors for output
        RED='\033[0;31m'
        GREEN='\033[0;32m'
        YELLOW='\033[1;33m'
        BLUE='\033[0;34m'
        NC='\033[0m' # No Color

        echo -e "${BLUE}=== Release Candidate Creator ===${NC}"
        echo ""

        # Check for required tools
        if ! command -v gh &> /dev/null; then
          echo -e "${RED}Error: gh CLI is not installed${NC}"
          echo "Install it from: https://cli.github.com/"
          exit 1
        fi

        # Check gh auth status
        if ! gh auth status &> /dev/null; then
          echo -e "${RED}Error: Not authenticated with gh CLI${NC}"
          echo "Run: gh auth login"
          exit 1
        fi

        # Read current version
        if [ ! -f "{{.VERSION_FILE}}" ]; then
          echo -e "${RED}Error: {{.VERSION_FILE}} file not found${NC}"
          exit 1
        fi

        CURRENT_VERSION=$(cat {{.VERSION_FILE}} | tr -d '[:space:]')
        echo -e "Current version: ${GREEN}${CURRENT_VERSION}${NC}"
        echo ""

        # Parse current version using cut (more portable than BASH_REMATCH)
        if ! echo "$CURRENT_VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo -e "${RED}Error: Invalid version format in {{.VERSION_FILE}}: $CURRENT_VERSION${NC}"
          echo "Expected format: MAJOR.MINOR.PATCH (e.g., 1.2.3)"
          exit 1
        fi

        MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
        MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
        PATCH=$(echo "$CURRENT_VERSION" | cut -d. -f3)

        # Ask user for bump type
        echo "What type of release is this?"
        echo ""
        echo -e "  ${YELLOW}1)${NC} major  - Breaking changes (${MAJOR}.${MINOR}.${PATCH} → $((MAJOR + 1)).0.0)"
        echo -e "  ${YELLOW}2)${NC} minor  - New features, backward compatible (${MAJOR}.${MINOR}.${PATCH} → ${MAJOR}.$((MINOR + 1)).0)"
        echo -e "  ${YELLOW}3)${NC} patch  - Bug fixes, backward compatible (${MAJOR}.${MINOR}.${PATCH} → ${MAJOR}.${MINOR}.$((PATCH + 1)))"
        echo ""
        read -p "Enter choice [1/2/3]: " CHOICE

        case $CHOICE in
          1|major)
            NEW_VERSION="$((MAJOR + 1)).0.0"
            BUMP_TYPE="major"
            ;;
          2|minor)
            NEW_VERSION="${MAJOR}.$((MINOR + 1)).0"
            BUMP_TYPE="minor"
            ;;
          3|patch)
            NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
            BUMP_TYPE="patch"
            ;;
          *)
            echo -e "${RED}Invalid choice: $CHOICE${NC}"
            exit 1
            ;;
        esac

        echo ""
        echo -e "Bump type: ${YELLOW}${BUMP_TYPE}${NC}"
        echo -e "New version: ${GREEN}${NEW_VERSION}${NC}"

        # Fetch tags to check for existing RCs
        echo ""
        echo "Fetching tags..."
        git fetch --tags --quiet

        # Find the next RC number for this version
        RC_NUM=0
        while git rev-parse "v${NEW_VERSION}-rc${RC_NUM}" &> /dev/null; do
          RC_NUM=$((RC_NUM + 1))
        done

        RC_TAG="v${NEW_VERSION}-rc${RC_NUM}"
        echo -e "Release candidate tag: ${GREEN}${RC_TAG}${NC}"
        echo ""

        # Confirm with user
        echo ""
        echo -e "Ready to create: ${GREEN}${RC_TAG}${NC}"
        echo -n "Proceed? [y/N]: "
        read CONFIRM
        if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
          echo -e "${YELLOW}Cancelled${NC}"
          exit 0
        fi

        # Create and push the tag
        echo ""
        echo "Creating tag ${RC_TAG}..."
        git tag -a "${RC_TAG}" -m "Release candidate ${RC_TAG}"

        echo "Pushing tag to origin..."
        git push origin "${RC_TAG}"

        echo ""
        echo -e "${GREEN}=== Success ===${NC}"
        echo -e "Tag ${GREEN}${RC_TAG}${NC} has been created and pushed."
        echo ""
        echo "Next steps:"
        echo "  1. The prepare-release workflow will create a PR"
        echo "  2. Review and merge the PR"
        echo "  3. The release will be automatically created"
        echo ""
        echo -e "View workflow: ${BLUE}$(gh repo view --json url -q .url)/actions${NC}"

  release-status:
    desc: Show the status of the current release
    silent: true
    cmds:
      - |
        #!/bin/bash
        set -e

        BLUE='\033[0;34m'
        GREEN='\033[0;32m'
        YELLOW='\033[1;33m'
        NC='\033[0m'

        echo -e "${BLUE}=== Release Status ===${NC}"
        echo ""

        # Current VERSION
        if [ -f "{{.VERSION_FILE}}" ]; then
          VERSION=$(cat {{.VERSION_FILE}} | tr -d '[:space:]')
          echo -e "VERSION file: ${GREEN}${VERSION}${NC}"
        else
          echo -e "VERSION file: ${YELLOW}not found${NC}"
        fi

        # Latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
        echo -e "Latest tag: ${GREEN}${LATEST_TAG}${NC}"

        # Latest RC tag
        LATEST_RC=$(git tag -l 'v*-rc*' --sort=-version:refname | head -1)
        if [ -n "$LATEST_RC" ]; then
          echo -e "Latest RC tag: ${YELLOW}${LATEST_RC}${NC}"
        fi

        # Open release PRs
        echo ""
        echo "Open release PRs:"
        gh pr list --label release --json number,title,url --template '{{range .}}  #{{.number}} {{.title}}{{"\n"}}    {{.url}}{{"\n"}}{{end}}' || echo "  None"

        # Recent releases
        echo ""
        echo "Recent releases:"
        gh release list --limit 5 || echo "  None"

  version:
    desc: Show the current version
    cmds:
      - cat {{.VERSION_FILE}}
